### ISSUE TITLE
Duplication of initialState declaration

### ISSUE THREAD

**Issue by rkusuma** [GregOnNet/ngrx-ducks-demo#1]
There is a duplication of initialState declaration

https://github.com/GregOnNet/ngrx-ducks-demo/blob/master/src/app/store/counter/counter.duck.ts#L11

and

https://github.com/GregOnNet/ngrx-ducks-demo/blob/master/src/app/store/counter/counter.reducer.ts#L8

Is there a way to avoid this?

**Comment by GregOnNet** [comment]
Hi,

thank you for reaching out.

The file https://github.com/GregOnNet/ngrx-ducks-demo/blob/master/src/app/store/counter/counter.reducer.ts#L8 is not used.
I just let it there for other to see the difference.

ngrx-ducks create the reducer function automatically.

Furthermore, today a new API for ngrx-ducks has been released.
The decorator API will be deprecated at some point in the future.

You can check out the new stuff at https://stackblitz.com/edit/ngrx-ducks-8-4?file=src%2Fapp%2Fcounter%2Fstore%2Fcounter%2Fcounter.facade.ts

Please feel free to reopen this issue if you have further questions.

Kinds
Gregor
